# permissions for end users to view projectclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projectclaim-viewer-role
rules:
- apiGroups:
  - gcp.managed.openshift.io.my.domain
  resources:
  - projectclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gcp.managed.openshift.io.my.domain
  resources:
  - projectclaims/status
  verbs:
  - get
